version: '3.8'

services:
  precalculus-assistant:
    build: .
    ports:
      - "7654:7654"
    volumes:
      - ./precalculus_docs:/app/precalculus_docs
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
    environment:
      - INIT_INDEX=false
      - HTTP_PORT=7654
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]